rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('meeteditors/', views.meeteditors, name='meeteditors'),
    path('logout/', views.user_logout, name='logout'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('goto/', views.goto_url, name='goto'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('watch_catalogue/', views.CatalogueView, name='watch_catalogue'),
    path('watch_more/<slug:category_name_slug>/', views.show_more, name='show_more'),
    path('post_comment/', views.PostCommentView.as_view(), name='post_comment'),
    path('prepare_chart_data/', views.prepare_chart_data, name='prepare_chart_data'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),

    # New line below -- don't forget the slash after register!
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),

    path('accounts/', include('registration.backends.simple.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    
    NAME_MAX_LENGTH = 128
    DESCRIPTION_MAX_LENGTH = 500
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    #Bingo watch attributes
    type = models.CharField(max_length=30,default='') #type of watch
    description = models.CharField(max_length=DESCRIPTION_MAX_LENGTH ,default='') #watch description
    recommend_buy = models.IntegerField(default=0) #recommended buy index
    url = models.URLField(blank=True) #watch vendor link
    picture = models.ImageField(upload_to='product_images', blank=True) #product image

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Page(models.Model):

    NAME_MAX_LENGTH = 128
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    #Bingo watch attributes
    description = models.CharField(max_length=500,default='')

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    #Bingo watch attributes
    background = models.CharField(max_length=500,default='')

    def __str__(self):
        return self.user.username

#Bingo watch object
#User comment
class Comment(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    content = models.CharField(max_length=500) #comment content
    rating = models.IntegerField(default=0) #rating
    log_datetime = models.DateTimeField(auto_now=True) #date time

    def __str__(self):
        return self.content[0:10]

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile
from django.db import models

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,
                            help_text="Please enter the watch name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    ##Updating the category form for bingo 
    type = forms.CharField(help_text="Please enter the watch type.")
    description = forms.CharField(max_length=Category.DESCRIPTION_MAX_LENGTH ,help_text="Please enter a description for the watch.")
    recommend_buy = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    picture = models.ImageField(upload_to='product_images', blank=True)




    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name', 'views', 'likes', 'slug', 'type', 'description', 'recommend_buy','url','picture')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data
        
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.NAME_MAX_LENGTH,
    help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
    help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    description = forms.CharField(max_length=500,help_text="Please enter description of the page.")


    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        #fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from rango.models import UserProfile, Comment
from rolepermissions.decorators import has_role_decorator
from django.http import JsonResponse

def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by the number of likes in descending order.
    # Retrieve the top 5 only -- or all if less than 5.
    # Place the list in our context_dict dictionary (with our boldmessage!)
    # that will be passed to the template engine.
    #category_list = Category.objects.order_by('-likes')[:5]
    #pages_list = Page.objects.order_by('-views')[:5]
    
    to_buy_category_list = Category.objects.order_by('-recommend_buy')[:5]
    to_avoid_category_list = Category.objects.order_by('recommend_buy')[:5]
    comments = Comment.objects.order_by('-log_datetime')[:10]
    

    context_dict = {}
    #context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    #context_dict['categories'] = category_list
    #context_dict['pages'] = pages_list
    context_dict['to_buy_lst'] = to_buy_category_list
    context_dict['not_to_buy_lst'] = to_avoid_category_list
    context_dict['comments'] = comments

    # Call the helper function to handle the cookies
    #visitor_cookie_handler(request)

    # Render the response and send it back!
    response = render(request, 'rango/index.html', context=context_dict)

    return response

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        #pages = Page.objects.filter(category=category)
        pages = Page.objects.filter(category=category).order_by('-views')
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category

    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

def about(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage matches to {{ boldmessage }} in the template!
    context_dict = {'myname': 'KK To'}

    # Call the helper function to handle the cookies
    visitor_cookie_handler(request)

    context_dict['visits'] = request.session['visits']

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.

    return render(request, 'rango/about.html', context=context_dict)

@login_required
@has_role_decorator('editor')
def add_category(request):
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            cat = form.save(commit=True)
            print(cat, cat.slug)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect(reverse('rango:show_category',
                                kwargs={'category_name_slug':cat.slug}))
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})
    
@login_required
@has_role_decorator('editor')
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                kwargs={'category_name_slug':
                                    category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):

    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    # Render the template depending on the context.
    return render(request,
                    'rango/register.html',context =
                    {'user_form': user_form, 'profile_form': profile_form, 'registered':registered})

def user_login(request):

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print ("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
            # The request is not a HTTP POST, so display the login form.
            # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html')

def meeteditors(request):
     return render(request, 'rango/editor.html')

# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
<div class="container">
<h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
</div>
</div>
<div class="container">
<div class="row">
<form role="form" id="page_form" method="post"
    action="{% url 'rango:add_page' category.slug %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}<br />
    {{ field }}<br />
    <div class="p-2"></div>
{% endfor %}
<br />
<button class="btn btn-primary" type="submit" name="submit" class="btn btn-primary">
Add Page
</button>
<div class="p-5"></div>
</form>
</div>
</div>
{% endblock %}

templates/rango/base.html
<!doctype html>
{% load staticfiles %}
{% load rango_template_tags %}
{% load permission_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>Bingo - {% block title_block %}Luxury Watch{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
  

    <!-- Bootstrap core CSS -->
    <!--<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Yrsa:400,600&display=swap" rel="stylesheet">  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">  
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/editor.css' %}" rel="stylesheet">
    
    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Bingo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item"><a class="nav-link" active" aria-current="page" href="{% url 'rango:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:watch_catalogue' %}">Luxury Watch Catalogue</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:meeteditors' %}">Meet Editors</a></li>
            <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
            {% if user.is_authenticated %}
              {% if user|has_role:'editor' %}
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        New Watch Management
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'rango:add_category' %}">Add Category</a></li>
                          <!--<li><a class="dropdown-item" href="#">Add Page</a></li>-->
                      </ul>                    
                  </li>
              {% endif %}           
            
            {% else %}
              <!--<li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>-->
            {% endif %}

        </ul>
          <form class="d-flex">
            <!--<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>-->
            {% if user.is_authenticated %}
              <a class="btn btn-outline-success" href="{% url 'auth_logout' %}?next=/rango/"><i class="bi bi-door-open-fill"></i> Logout</a>
            {% else %}
              <a class="btn btn-outline-success" href="{% url 'auth_login' %}"><i class="bi bi-person-circle"></i> Login</a>
            {% endif %}
          </form>
      </div>
    </div>
  </nav>
</header>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <p></p>
                {% block sidebar_block %}
                    {% get_category_list category %}
                {% endblock %}
            </div>
        </nav>
        
        <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
            {% block body_block %}{% endblock %}
            
            <!-- FOOTER -->
            <footer class="container">
                <p class="float-end"><a href="#">Back to top</a></p>
                <p>&copy; 2021 Bingo Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
            </footer>
        </main>
    </div>
</div>

    <!--<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>  
    <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/rango/base_chart.html
<!doctype html>
{% load staticfiles %}
{% load rango_template_tags %}
{% load permission_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>Bingo - {% block title_block %}Luxury Watch{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
  

    <!-- Bootstrap core CSS -->
    <!--<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Bingo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item"><a class="nav-link" active" aria-current="page" href="{% url 'rango:index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:watch_catalogue' %}">Luxury Watch Catalogue</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:meeteditors' %}">Meet Editors</a></li>
            <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
            {% if user.is_authenticated %}
              {% if user|has_role:'editor' %}
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        New Watch Management
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'rango:add_category' %}">Add Category</a></li>
                          <!--<li><a class="dropdown-item" href="#">Add Page</a></li>-->
                      </ul>                    
                  </li>
              {% endif %}           
            
            {% else %}
              <!--<li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>-->
            {% endif %}

        </ul>
          <form class="d-flex">
            <!--<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>-->
            {% if user.is_authenticated %}
              <a class="btn btn-outline-success" href="{% url 'auth_logout' %}?next=/rango/"><i class="bi bi-door-open-fill"></i> Logout</a>
            {% else %}
              <a class="btn btn-outline-success" href="{% url 'auth_login' %}"><i class="bi bi-person-circle"></i> Login</a>
            {% endif %}
          </form>
      </div>
    </div>
  </nav>
</header>

<main>

  {% block body_block %}{% endblock %}

  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2021 Bingo Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <!--<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>  
    <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>

    <!--chartjs integration-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static "js/watch_chart.js" %}" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <div class="jumbotron p-4">
            <div class="container">
            <h1 class="jumbotron-heading">{{ category.name }}</h1>
            
                <strong id="like_count">{{ category.likes }}</strong> likes
                {% if user.is_authenticated %}
                <!--<button id="like_btn"
                data-categoryid="{{ category.id }}"
                class="btn btn-primary btn-sm"
                type="button">
                <span data-feather="thumbs-up"></span>
                Like Category
                </button>-->
                {% endif %}
                        
            </div>
        </div>        
        <div class="container">
            <div class="row">       
                {% if pages %}
                    <ul>
                    {% for page in pages %}
                        <li>
                        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}" target="_blank">{{ page.title }}</a>
                        {% if page.views > 1 %}
                            ({{ page.views }} views)
                        {% elif page.views == 1 %}
                            ({{ page.views }} view)
                        {% endif %}
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages currently in category.</strong>
                {% endif %}
                {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
                {% endif %}
            </div>
        </div>
    {% else %}
        Unkown Category
    {% endif %}
            
{% endblock %}